---
sidebar: sidebar 
permalink: docs/hci_prereqs_network_cables.html 
summary: Saiba mais sobre os requisitos do cabo de rede NetApp HCI. 
keywords: netapp, hci, network, cable, requirements 
---
= Requisitos do cabo de rede
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode usar as diretrizes a seguir para garantir que você tenha o tipo adequado de cabos de rede para o tamanho de sua implantação. Para portas RJ45, você deve usar cabos com classificação Cat 5e ou Cat 6.

* Configuração de nó de computação de dois cabos: Cada nó de computação deve ser conetado a uma rede 10G/25GbEG por meio de duas interfaces SFP mais de SFP28G (um cabo Cat 5eG/6G adicional é opcional para gerenciamento fora da banda).
* Configuração de nó de computação de seis cabos: Cada nó de computação deve ser conetado a uma rede 10/25GbE por meio de quatro interfaces SFP mais/SFP28 e a uma rede 1/10GbE por meio de dois cabos Cat 5e/6 (um cabo Cat 5e/6 adicional é opcional para gerenciamento fora da banda).
* Cada nó de armazenamento deve ser conetado a uma rede 10G/25GbEG por meio de duas interfaces SFP mais/SFP28G e a uma rede 1G/10GbEG por meio de dois cabos Cat 5ee/6e (um cabo Cat 5ee/6e adicional é opcional para gerenciamento fora da banda).
* Certifique-se de que os cabos de rede que utiliza para ligar o sistema NetApp HCI à sua rede são suficientemente longos para alcançar confortavelmente os seus switches.


Por exemplo, uma implantação que contenha quatro nós de storage e três nós de computação (usando a configuração de seis cabos) requer o seguinte número de cabos de rede:

* (14) cabos Cat 5e/6 com conetores RJ45 (mais sete cabos para tráfego IPMI, se desejado)
* (20) cabos Twinax com conetores SFP28/SFP


Isso se deve às seguintes razões:

* Quatro nós de storage exigem oito (8) cabos Cat 5e/6 e oito (8) cabos Twinax.
* Três nós de computação que usam a configuração de seis cabos requerem seis (6) cabos Cat 5e/6 e doze (12) cabos Twinax.



NOTE: Em uma configuração de seis cabos, duas portas são reservadas para o VMware ESXi e configuradas e gerenciadas pelo mecanismo de implantação do NetApp. Não é possível acessar ou gerenciar essas portas dedicadas ao ESXi usando o elemento TUI ou a interface gráfica do elemento.

[discrete]
== Encontre mais informações

* https://www.netapp.com/hybrid-cloud/hci-documentation/["Página de recursos do NetApp HCI"^]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in do NetApp Element para vCenter Server"^]

