---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_compute_firmware_ansible.html 
summary: Para nós de computação da série H, o NetApp fornece uma função Ansible que ajuda a automatizar a atualização do firmware para componentes de hardware, como BMC, BIOS e NIC. 
keywords: netapp, hci, on premise, cluster, element, compute node, ansible upgrade, upgrade role 
---
= Automatize as atualizações de firmware de nós de computação com o Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode atualizar o firmware do sistema em nós de computação do NetApp HCI, incluindo firmware para componentes como BMC, BIOS e NIC usando fluxos de trabalho no Controle de nuvem híbrida do NetApp. Para instalações com grandes clusters de computação, é possível automatizar os fluxos de trabalho com o Ansible para realizar uma atualização progressiva de todo o cluster.


NOTE: Embora a função Ansible para automatizar as atualizações de firmware de nós de computação seja disponibilizada pelo NetApp, a automação é um componente auxiliar que requer configuração adicional e a execução de componentes de software. A modificação da automação do Ansible é suportada apenas no melhor esforço.


NOTE: A função Ansible para upgrades funciona apenas nos nós de computação da série H da NetApp HCI. Você não pode usar essa função para atualizar nós de computação de terceiros.

.O que você vai precisar
* *Disponibilidade e pré-requisitos para atualizações de firmware*: A instalação do NetApp HCI deve estar pronta para atualização de firmware, conforme descrito nas instruções do link:task_hcc_upgrade_compute_node_firmware.html["a efetuar atualizações de firmware"].
* *Prontidão para executar a automação no nó de controle do Ansible*: Um servidor físico ou virtual para executar a automação de atualizações de firmware no Ansible.


.Sobre esta tarefa
Em um ambiente de produção, você deve atualizar os nós de computação em um cluster em uma instalação do NetApp HCI de forma contínua; um nó após o outro, um nó de cada vez. Orquestre o processo geral de atualização do firmware do nó de computação para um único nó de computação, incluindo a execução de verificações de integridade, colocação do ESXi nos nós de computação em manutenção e reinicialização do nó de computação para aplicar as atualizações de firmware NetApp. A função Ansible oferece a opção de orquestrar a atualização de firmware para um grupo de nós de computação ou clusters inteiros.

.Comece a usar a automação de atualização de firmware
Para começar, navegue até o https://github.com/NetApp-Automation/nar_compute_firmware_upgrade["Repositório do NetApp Ansible no GitHub"^] e faça o download da `nar_compute_nodes_firmware_upgrades` função e da documentação.
