---
sidebar: sidebar 
permalink: docs/task_mnode_ssh_management.html 
summary: Você pode desabilitar e habilitar o recurso SSH no nó de gerenciamento usando a IU do Controle de nuvem híbrida da NetApp ou a IU da API REST ou determinar o status da capacidade de conexão de suporte a SSH usando a IU da API REST. 
keywords: netapp, mnode, management node, ssh, disable, enable, rest api, hybrid, cloud, control, hcc 
---
= Gerencie a funcionalidade SSH no nó de gerenciamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode desativar, reativar ou determinar o status da capacidade SSH no nó de gerenciamento (mNode) usando a API REST. O recurso SSH que fornece link:task_mnode_enable_remote_support_connections.html["Acesso à sessão do túnel de suporte remoto (RST) do suporte da NetApp"] é desativado por padrão nos nós de gerenciamento que executam serviços de gerenciamento 2,18 ou posterior.

A partir dos Serviços de Gerenciamento 2.20.69, você pode ativar e desativar a capacidade SSH no nó de gerenciamento usando a IU do Controle de nuvem híbrida da NetApp.

.O que você vai precisar
* *Permissões de controle de nuvem híbrida da NetApp*: Você tem permissões como administrador.
* *Permissões de administrador de cluster*: Você tem permissões como administrador no cluster de armazenamento.
* *Element software*: Seu cluster está executando o software NetApp Element 11,3 ou posterior.
* *Nó de gerenciamento*: Você implantou um nó de gerenciamento executando a versão 11,3 ou posterior.
* *Atualizações de serviços de gestão*:
+
** Para usar a IU do Controle de nuvem híbrida da NetApp, você atualizou o https://mysupport.netapp.com/site/products/all/details/mgmtservices/downloads-tab["pacote de serviços de gerenciamento"^] para a versão 2.20.69 ou posterior.
** Para usar a IU da API REST, você atualizou o https://mysupport.netapp.com/site/products/all/details/mgmtservices/downloads-tab["pacote de serviços de gerenciamento"^] para a versão 2,17.




.Opções
* <<Desative ou ative o recurso SSH no nó de gerenciamento usando a IU do Controle de nuvem híbrida do NetApp>>


Você pode executar qualquer uma das seguintes tarefas depois de link:task_mnode_api_get_authorizationtouse.html["autenticar"]:

* <<Desative ou ative o recurso SSH no nó de gerenciamento usando APIs>>
* <<Determine o status do recurso SSH no nó de gerenciamento usando APIs>>




== Desative ou ative o recurso SSH no nó de gerenciamento usando a IU do Controle de nuvem híbrida do NetApp

Você pode desativar ou reativar a capacidade SSH no nó de gerenciamento. O recurso SSH que fornece link:task_mnode_enable_remote_support_connections.html["Acesso à sessão do túnel de suporte remoto (RST) do suporte da NetApp"] é desativado por padrão nos nós de gerenciamento que executam serviços de gerenciamento 2,18 ou posterior. A desativação do SSH não termina nem desliga sessões de cliente SSH existentes para o nó de gerenciamento. Se você desabilitar o SSH e optar por reativá-lo posteriormente, poderá fazê-lo usando a IU do Controle de nuvem híbrida da NetApp.


NOTE: Para ativar ou desativar o acesso de suporte usando SSH para um cluster de armazenamento, você deve usar o https://docs.netapp.com/us-en/element-software/storage/task_system_manage_cluster_enable_and_disable_support_access.html["Página de configurações do cluster da IU do Element"^].

.Passos
. No Painel, selecione o menu de opções no canto superior direito e selecione *Configurar*.
. Na tela *Support Access for Management Node*, alterne o switch para ativar o SSH do nó de gerenciamento.
. Depois de concluir a solução de problemas, na tela *Support Access for Management Node*, alterne o switch para desativar o SSH do nó de gerenciamento.




== Desative ou ative o recurso SSH no nó de gerenciamento usando APIs

Você pode desativar ou reativar a capacidade SSH no nó de gerenciamento. O recurso SSH que fornece link:task_mnode_enable_remote_support_connections.html["Acesso à sessão do túnel de suporte remoto (RST) do suporte da NetApp"] é desativado por padrão nos nós de gerenciamento que executam serviços de gerenciamento 2,18 ou posterior. A desativação do SSH não termina nem desliga sessões de cliente SSH existentes para o nó de gerenciamento. Se você desabilitar o SSH e optar por reativá-lo posteriormente, poderá fazê-lo usando a mesma API.

.Comando API
Para serviços de gerenciamento 2,18 ou posterior:

[listing]
----
curl -k -X PUT "https://<<ManagementNodeIP>/mnode/2/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----
Para serviços de gerenciamento 2,17 ou anteriores:

[listing]
----
curl -X PUT "https://<ManagementNodeIP>/mnode/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----

NOTE: Você pode encontrar o `${TOKEN}` portador usado pelo comando API quando link:task_mnode_api_get_authorizationtouse.html["autorizar"]você . O portador `${TOKEN}` está na resposta de ondulação.

.ETAPAS DA IU DA API REST
. Acesse a IU da API REST do serviço API do nó de gerenciamento inserindo o endereço IP do nó de gerenciamento seguido de `/mnode/`:
+
[listing]
----
https://<ManagementNodeIP>/mnode/
----
. Selecione *autorizar* e preencha o seguinte:
+
.. Introduza o nome de utilizador e a palavra-passe do cluster.
.. Introduza a ID do cliente como `mnode-client`.
.. Selecione *autorizar* para iniciar uma sessão.
.. Feche a janela.


. Na IU da API REST, selecione *PUT /settings​/ssh*.
+
.. Clique em *Experimente*.
.. Defina o parâmetro *Enabled* como `false` para desativar SSH ou `true` para reativar a capacidade SSH que foi anteriormente desativada.
.. Clique em *Executar*.






== Determine o status do recurso SSH no nó de gerenciamento usando APIs

Você pode determinar se a capacidade SSH está ou não ativada no nó de gerenciamento usando uma API de serviço de nó de gerenciamento. O SSH é desativado por padrão nos nós de gerenciamento que executam serviços de gerenciamento 2,18 ou posterior.

.Comando API
Para serviços de gerenciamento 2,18 ou posterior:

[listing]
----
curl -k -X PUT "https://<<ManagementNodeIP>/mnode/2/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----
Para serviços de gerenciamento 2,17 ou anteriores:

[listing]
----
curl -X PUT "https://<ManagementNodeIP>/mnode/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----

NOTE: Você pode encontrar o `${TOKEN}` portador usado pelo comando API quando link:task_mnode_api_get_authorizationtouse.html["autorizar"]você . O portador `${TOKEN}` está na resposta de ondulação.

.ETAPAS DA IU DA API REST
. Acesse a IU da API REST do serviço API do nó de gerenciamento inserindo o endereço IP do nó de gerenciamento seguido de `/mnode/`:
+
[listing]
----
https://<ManagementNodeIP>/mnode/
----
. Selecione *autorizar* e preencha o seguinte:
+
.. Introduza o nome de utilizador e a palavra-passe do cluster.
.. Introduza a ID do cliente como `mnode-client`.
.. Selecione *autorizar* para iniciar uma sessão.
.. Feche a janela.


. Na IU da API REST, selecione *GET /settings​/ssh*.
+
.. Clique em *Experimente*.
.. Clique em *Executar*.






== Encontre mais informações

https://docs.netapp.com/us-en/vcp/index.html["Plug-in do NetApp Element para vCenter Server"^]
