---
sidebar: sidebar 
permalink: docs/task_hci_manage_overview.html 
summary: Você pode configurar o FQDM e gerenciar credenciais para NetApp HCI, contas de usuário, clusters de storage, volumes, grupos de acesso a volume, iniciadores, políticas de QoS de volume e o nó de gerenciamento. 
keywords: netapp, hci, install, deploy, get started, configure, fqdn, fully qualified domain name 
---
= Visão geral do gerenciamento do NetApp HCI
:allow-uri-read: 


[role="lead"]
Você pode configurar o nome de domínio totalmente qualificado e gerenciar credenciais para NetApp HCI, contas de usuário, clusters de armazenamento, volumes, grupos de acesso a volume, iniciadores, políticas de QoS de volume e o nó de gerenciamento.

Aqui estão os itens com os quais você pode trabalhar:

* link:task_nde_access_ui_fqdn.html["Configure o acesso totalmente qualificado à IU da Web do Domain Name"]
* link:task_post_deploy_credentials.html["Alterar credenciais no NetApp HCI"]
* link:task_hci_credentials_vcenter_esxi.html["Atualize as credenciais do vCenter e do ESXi"]
* link:task_hcc_manage_storage_overview.html["Gerenciar ativos de storage do NetApp HCI"]
* link:task_mnode_work_overview.html["Trabalhe com o nó de gerenciamento"]
* link:concept_nde_hci_power_off_on.html["Desligue ou ligue o sistema NetApp HCI"]

