---
sidebar: sidebar 
permalink: docs/task_hci_upgrade_all_vsphere.html 
summary: Você pode atualizar o VMware Components para um NetApp HCI e executar etapas adicionais para reinstalar o vCenter Plug-in. 
keywords: netapp, hci, vSphere components, upgrade, vCenter, ESXi 
---
= Atualize seus componentes vSphere para um sistema NetApp HCI com o plug-in Element para vCenter Server
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Quando você atualiza os componentes do VMware vSphere da instalação do NetApp HCI, há algumas etapas adicionais que você precisará executar para o plug-in Element para vCenter Server.

.Passos
. Para atualizações do vCSA, https://docs.netapp.com/us-en/vcp/vcp_task_qossioc.html#clear-qossioc-settings["limpar"^] as configurações do QoSSIOC no plug-in (*Configuração do NetApp Element > Configurações do QoSSIOC*). O campo *Status do QoSSIOC* é exibido `Not Configured` após o processo estar concluído.
. Para atualizações do vCSA e do Windows, https://docs.netapp.com/us-en/vcp/task_vcp_unregister.html["anular registo"^] o plug-in do vCenter Server ao qual ele está associado usando o utilitário de Registro.
. https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vcenter.upgrade.doc/GUID-7AFB6672-0B0B-4902-B254-EE6AE81993B2.html["Atualize o vSphere, incluindo vCenter Server, ESXi, VMs e outros componentes VMware"^].
+
[IMPORTANT]
====
Você deve atualizar para o plug-in do NetApp Element para vCenter Server 5,0 ou posterior para oferecer a capacidade de implantar o plug-in com o VMware vCenter 7,0 Update 3 sem precisar aplicar uma solução alternativa.

Com o Element Plug-in para vCenter Server 4.x, quando você atualiza para o VMware vCenter Server 7,0 Update 3, o plug-in 4.x não consegue implantar. Para resolver esse problema usando o Spring Framework 4, https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/vCenter_plug-in_deployment_fails_after_upgrading_vCenter_to_version_7.0_U3["Este artigo da KB"^] consulte .

====
+

NOTE: Ao atualizar o ESXi para nós de computação para um https://www.netapp.com/pdf.html?item=/media/9489-tr-4823.pdf["cluster de dois nós"^], atualize apenas um nó de computação de cada vez para que apenas um nó de testemunha fique temporariamente indisponível e o quorum do cluster possa ser mantido.

. https://docs.netapp.com/us-en/vcp/vcp_task_getstarted.html#register-the-plug-in-with-vcenter["Registe-se"^] O plug-in Element para vCenter Server novamente com o vCenter.
. https://docs.netapp.com/us-en/vcp/vcp_task_getstarted.html#add-storage-clusters-for-use-with-the-plug-in["Adicionar clusters"^] utilizar o plug-in.
. https://docs.netapp.com/us-en/vcp/vcp_task_getstarted.html#configure-qossioc-settings-using-the-plug-in["Configure as configurações do QoSSIOC"^] utilizar o plug-in.
. https://docs.netapp.com/us-en/vcp/vcp_task_qossioc.html#enabling-qossioc-automation-on-datastores["Ative o QoSSIOC"^] para todos os datastores controlados pelo plug-in.




== Encontre mais informações

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in do NetApp Element para vCenter Server"^]
* https://www.netapp.com/pdf.html?item=/media/9489-tr-4823.pdf["Relatório técnico de clusters de storage de dois nós da NetApp HCI"^]

