---
sidebar: sidebar 
permalink: docs/task_nde_configure_credentials.html 
summary: Saiba como configurar o VMware vSphere durante a implantação do NetApp HCI. 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= Configurando credenciais NetApp HCI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante a implantação, você define um conjunto de credenciais a serem usadas no ambiente VMware vSphere recém-implantado, nos recursos de computação e storage da NetApp HCI e no nó de gerenciamento. Se você estiver implantando o NetApp HCI em um ambiente vSphere existente, essas credenciais não serão aplicadas ao vCenter Server existente.

.Sobre esta tarefa
Lembre-se dos seguintes pontos sobre as credenciais definidas no mecanismo de implantação do NetApp HCI:

* *Controle de nuvem híbrida (HCC) da NetApp ou IU do Element*: Para fazer login no HCC da NetApp ou na interface do usuário do Element após a implantação bem-sucedida, use o nome de usuário e a senha especificados nesta etapa de implantação.
* *VMware vCenter*: Para fazer login no vCenter (se instalado como parte da implantação), use o nome de usuário com o sufixo `@vsphere.local` ou a conta de usuário integrada `Administrator@vsphere.local` e a senha especificada nesta etapa de implantação.
* *VMware ESXi*: Para fazer login no ESXi nos nós de computação, use o nome de usuário `root` e a mesma senha especificada nesta etapa de implantação.


Para interação com instâncias do VMware vCenter, o controle de nuvem híbrida da NetApp usará um dos seguintes procedimentos:

* A `Administrator@vsphere.local` conta de usuário integrada na instância do vCenter que foi instalada como parte da implantação.
* As credenciais do vCenter que foram usadas para conetar a implantação do NetApp HCI a um VMware vCenter Server existente.


.Passos
. Na página *credenciais*, insira um nome de usuário no campo *Nome de usuário*.
. Introduza uma palavra-passe no campo *Palavra-passe*. A senha deve estar em conformidade com os critérios de senha visíveis na caixa *Senha deve conter*.
. Confirme a palavra-passe no campo *Introduza novamente a palavra-passe*.
. Clique em *continuar*.


[discrete]
== Encontre mais informações

* link:firmware_driver_versions.html["Versões de firmware e driver ESXi compatíveis para versões de NetApp HCI e firmware para nós de storage NetApp HCI"]
* Para atualizar as credenciais do vCenter e do ESXi posteriormente, link:task_hci_credentials_vcenter_esxi.html["Atualize as credenciais do vCenter ou do ESXi"]consulte .

