---
sidebar: sidebar 
permalink: docs/task_hci_credentials_vcenter_esxi.html 
summary: Em uma instalação do NetApp HCI, você pode alterar credenciais para o vCenter e seus hosts ESXi para um nó de computação gerenciado pelo Controle de nuvem híbrida da NetApp. 
keywords: netapp, hci, password, credential, vcenter, esxi, hybrid cloud control 
---
= Atualize as credenciais do vCenter e do ESXi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para manter todos os recursos do Controle de nuvem híbrida da NetApp para sua instalação do NetApp HCI, quando você altera suas credenciais em hosts do vCenter e ESXi, você também precisa atualizar essas credenciais no serviço de ativos no nó de gerenciamento.

.Sobre esta tarefa
O controle de nuvem híbrida do NetApp se comunica com o vCenter e com os nós de computação individuais que executam o VMware vSphere ESXi para recuperar informações do painel e facilitar atualizações contínuas de firmware, software e drivers. O Controle de nuvem híbrida da NetApp e seus serviços relacionados no nó de gerenciamento usam credenciais (nome de usuário/senha) para se autenticar no VMware vCenter e no ESXi.

Se a comunicação entre esses componentes falhar, o Controle de nuvem híbrida do NetApp e o vCenter exibem mensagens de erro quando ocorrem problemas de autenticação. O Controle de nuvem híbrida do NetApp exibirá um banner de erro vermelho se ele não puder se comunicar com a instância associada do VMware vCenter na instalação do NetApp HCI. O VMware vCenter exibirá mensagens de bloqueio de conta ESXi para hosts ESXi individuais como resultado do Controle de nuvem híbrida do NetApp usando credenciais desatualizadas.

O nó de gerenciamento no NetApp HCI refere-se a esses componentes usando os seguintes nomes:

* "Ativos do controlador" são instâncias do vCenter associadas à instalação do NetApp HCI.
* "Ativos de nó de computação" são os hosts ESXi em sua instalação do NetApp HCI.


Durante a instalação inicial do NetApp HCI usando o mecanismo de implantação do NetApp, o nó de gerenciamento armazenou as credenciais do usuário administrativo especificado para o vCenter e a senha da conta "raiz" nos servidores ESXi.



== Atualize a senha do vCenter usando a API REST do nó de gerenciamento

Siga as etapas para atualizar os ativos do controlador. link:task_mnode_edit_vcenter_assets.html["Visualizar ou editar ativos de controlador existentes"]Consulte .



== Atualize a senha do ESXi usando a API REST do nó de gerenciamento

.Passos
. Para obter uma visão geral da interface do usuário REST API do nó de gerenciamento, consulte link:task_mnode_work_overview_API.html["Visão geral da interface do usuário da API REST do nó de gerenciamento"].
. Acesse a IU da API REST para serviços de gerenciamento no nó de gerenciamento:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
+
Substitua IP do nó de gerenciamento pelo endereço IPv4 do nó de gerenciamento na rede de gerenciamento usada para o NetApp HCI.

. Clique em *autorizar* ou em qualquer ícone de cadeado e complete o seguinte:
+
.. Introduza o nome de utilizador e a palavra-passe administrativos do cluster do NetApp SolidFire.
.. Introduza a ID do cliente como `mnode-client`.
.. Clique em *autorizar* para iniciar uma sessão.
.. Feche a janela.


. Na IU da API REST, clique em *GET ​/assets/Compute_nodes*.
+
Isso recupera os Registros de ativos de nó de computação que são armazenados no nó de gerenciamento.

+
Aqui está o link direto para esta API na IU:

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.get_compute_nodes
----
. Clique em *Experimente*.
. Clique em *Executar*.
. No corpo da resposta, identifique os Registros de ativos de nós de computação que precisam de credenciais atualizadas. Você pode usar as propriedades "ip" e "host_name" para encontrar os Registros corretos do host ESXi.
+
[listing]
----
"config": { },
"credentialid": <credential_id>,
"hardware_tag": <tag>,
"host_name": <host_name>,
"id": <id>,
"ip": <ip>,
"parent": <parent>,
"type": ESXi Host
----
+

NOTE: A próxima etapa usa os campos "pai" e "id" no Registro de ativos de computação para referenciar o Registro a ser atualizado.

. Configure o ativo de nó de computação específico:
+
.. Clique em *PUT /assets/(Asset_id)/Compute-nonos/(Compute_id)*.
+
Aqui está o link direto para a API na IU:

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.put_assets_compute_id
----
.. Clique em *Experimente*.
.. Insira o "Asset_id" com as informações "pai".
.. Digite "Compute_id" com a informação "id".
.. Modifique o corpo da solicitação na interface do usuário para atualizar somente os parâmetros de senha e nome de usuário no Registro de ativos de computação:
+
[listing]
----
{
"password": "<password>",
"username": "<username>"
}
----
.. Clique em *Executar*.
.. Valide que a resposta é HTTP 200, o que indica que as novas credenciais foram armazenadas no Registro de ativos de computação referenciados


. Repita as duas etapas anteriores para ativos de nós de computação adicionais que precisam ser atualizados com uma nova senha.
. Navegue até https://<mNode_ip>/inventory/1/[].
+
.. Clique em *autorizar* ou em qualquer ícone de cadeado e complete o seguinte:
+
... Introduza o nome de utilizador e a palavra-passe administrativos do cluster do NetApp SolidFire.
... Introduza a ID do cliente como `mnode-client`.
... Clique em *autorizar* para iniciar uma sessão.
... Feche a janela.


.. Na IU da API REST, clique em *GET /installations*.
.. Clique em *Experimente*.
.. Selecione *True* na lista suspensa Atualizar descrição.
.. Clique em *Executar*.
.. Valide que a resposta é HTTP 200.


. Aguarde cerca de 15 minutos para que a mensagem de bloqueio de conta no vCenter desapareça.




== Encontre mais informações

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in do NetApp Element para vCenter Server"^]

